#!/bin/bash

#Сделайте скрипт, который спросит имя пользователя и скажет, является ли пользователь администратором


read -p "Enter loggin: " username 
user_groups=$(id $username) 


if [[ $user_groups == *"sudo"* ]]; then
	echo "This user is administrator"
else
	echo "This user isn't administrator" 
fi
