#!/bin/bash

#Создайте файл со списком пользователей. С помощью for выведите на экран текст
#: «Creating new user: useradd имя_пользователя».

file="/home/hik/Desktop/Scripts/list_users"

for var in $(cat $file)
do
echo "Creating new user: useradd $var"
done
